[project]
name = 'super_fun_contrat'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.file_tagging]
path = 'contracts/file_tagging.clar'
clarity_version = 2
epoch = 2.5

[contracts.funding]
path = 'contracts/funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.multiple_voting_rounds]
path = 'contracts/multiple_voting_rounds.clar'
clarity_version = 2
epoch = 2.5

[contracts.timed_storage_update]
path = 'contracts/timed_storage_update.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
